openapi: 3.0.0
info:
  title: Customer Support
  version: 0.1.0
  description: Customer Support

tags:
  - name: Order Details
    description: Order Details
  - name: Email Details
    description: Operations related to mail retrieval

servers:
  - url: https://order-to-cash.1zm3ivaj16pu.us-south.codeengine.appdomain.cloud

paths:
  /get_order_updates/{order_id}:
    get:
      summary: Get Order Details
      description: Get Order Details
      operationId: get_order_details_po_get
      tags:
        - Order Details
      parameters:
        - name: order_id
          in: path
          required: true
          schema:
            type: string
            title: Order ID
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderDetails"

  /get_all_orders:
    get:
      summary: Get All Orders
      description: Retrieves all order IDs
      operationId: get_all_orders
      tags:
        - Order Details
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderIds"

  /get_all_mails:
    get:
      summary: Get All Mails
      description: Fetches all mail records
      operationId: get_all_mails
      tags:
        - Email Details
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MailRecords"

components:
  schemas:
    OrderIds:
      type: object
      properties:
        Orders:
          type: object
          additionalProperties:
            type: string

    OrderDetails:
      type: object
      properties:
        Order_Update:
          type: array
          items:
            type: object
            properties:
              order_id:
                type: string
              order_date:
                type: string
              order_update:
                type: string

    MailRecords:
      type: object
      properties:
        Mail_Records:
          type: object
          properties:
            name:
              type: object
              additionalProperties:
                type: string
            email:
              type: object
              additionalProperties:
                type: string

    HTTPValidationError:
      type: object
      title: HTTPValidationError
      properties:
        detail:
          type: array
          title: Detail
          items:
            $ref: "#/components/schemas/ValidationError"

    ValidationError:
      type: object
      title: ValidationError
      required:
        - loc
        - msg
        - type
      properties:
        loc:
          type: array
          title: Location
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
