openapi: 3.0.0
info:
  title: Order Management
  version: 0.1.0
  description: Order Management

tags:
  - name: PO Details
    description: Operations related to order details
  - name: Quotation Details
    description: Get Quotation Details
  - name: All POs Details
    description: Get all POs
  - name: Matching Results
    description: Get Matching Results
  - name: Display Confirmation
    description: Display Confirmation

servers:
  - url: https://order-to-cash.1zm3ivaj16pu.us-south.codeengine.appdomain.cloud

paths:
  /get_all_pos:
    get:
      summary: Get all PO Details
      description: Fetch all Purchase Orders
      operationId: fetch_all_po_details
      tags:
        - All POs Details
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AllPODetails"

  /po/{po_number}:
    get:
      summary: Get PO Details
      description: Get PO Details
      operationId: get_po_details_po_get
      tags:
        - PO Details
      parameters:
        - name: po_number
          in: path
          required: true
          schema:
            type: string
            title: PO Number
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PODetails"

  /quotation/{quotation_number}:
    get:
      summary: Get Quotation Details
      description: Get Quote Details
      operationId: get_quotation_details
      tags:
        - Quotation Details
      parameters:
        - name: quotation_number
          in: path
          required: true
          schema:
            type: string
            title: Quotation Number
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuotationDetails"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"

  /matching_results/:
    get:
      summary: Get Matching Results
      description: Get Matching Results
      operationId: get_matching_results
      tags:
        - Matching Results
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatchingResults"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"

  /display_confirmation/:
    get:
      summary: Display Confirmation
      description: Display Confirmation
      operationId: display_confirmation
      tags:
        - Display Confirmation
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DisplayConfirmation"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"

components:
  schemas:
    AllPODetails:
      type: object
      properties:
        PO_Records:
          type: array
          items:
            type: object
            properties:
              pom_id:
                type: string
                description: POM ID
              po_number:
                type: string
                description: PO Number
              submitted_by:
                type: string
                description: Submitted by
              user_id:
                type: string
                description: User ID

    PODetails:
      type: object
      properties:
        PO_Details:
          type: array
          items:
            type: object
            properties:
              po_date:
                type: string
              po_number:
                type: string
              payment_terms:
                type: string
              quote_number:
                type: string
              bill_to_party_name:
                type: string
              bill_to_party_address:
                type: string
              bill_to_party_gstin:
                type: string
              ship_to_party_name:
                type: string
              ship_to_party_address:
                type: string
              ship_to_party_gstin:
                type: string
              product_desc:
                type: string
              qty:
                type: string
              unit_rate:
                type: string
              taxable_value:
                type: string
              total_amount:
                type: string

    QuotationDetails:
      type: object
      properties:
        Quotation_Details:
          type: array
          items:
            type: object
            properties:
              quotation_number:
                type: string
              bill_to_party_name:
                type: string
              bill_to_party_address:
                type: string
              bill_to_party_gstin:
                type: string
              ship_to_party_name:
                type: string
              ship_to_party_address:
                type: string
              ship_to_party_gstin:
                type: string
              product_desc:
                type: string
              qty:
                type: string
              unit_rate:
                type: string
              taxable_value:
                type: string
              total_amount:
                type: string

    MatchingResults:
      type: object
      properties:
        Validation_Details:
          type: array
          items:
            type: object
            properties:
              entity_name:
                type: string
              po_details:
                type: string
              quotation_details:
                type: string
              matching_result:
                type: string

    DisplayConfirmation:
      type: object
      properties:
        Confirmation_Message:
          type: string

    HTTPValidationError:
      type: object
      properties:
        detail:
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"

    ValidationError:
      type: object
      required:
        - loc
        - msg
        - type
      properties:
        loc:
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          type: string
        type:
          type: string
